version: '3.8'
services:
  web:
    build: ./src/
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: kaufon/database:1.0
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}